//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by 我的任务.rc
//
#define IDC_BTN_HIDE                    2
#define ID_DETAILS                      2
#define IDC_BTN_QUIT_EDIT               3
#define ID_MESDLG_OK                    3
#define ID_MESDLG_CANCEL                4
#define IDM_ABOUTBOX                    0x0010
#define ID_MENU_EXIT                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MY_DIALOG                   102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME_BLACK             128
#define IDR_MENU_MAIN                   129
#define IDR_MAINFRAME1                  129
#define IDR_MAINFRAME                   130
#define IDR_MAINFRAME2                  131
#define IDR_TOOLBAR_MAIN                132
#define IDR_MENU_LIST_POP               136
#define IDD_DIALOG_MSG                  137
#define IDD_DIALOG_SET                  140
#define IDR_MENU_TRAY                   144
#define IDD_DIALOG_MSG_HANDLE           145
#define IDD_DIALOG_HANDLE_MSG           148
#define IDD_DIALOG_SUBMIT               150
#define IDB_BITMAP_BTN_GEN              161
#define IDB_BITMAP_BTN_FOCUS            162
#define IDB_BITMAP_BTN_SEL              163
#define IDB_BITMAP_BTN_GRAY             164
#define IDB_BITMAP1                     181
#define IDB_BITMAP2                     182
#define IDB_BITMAP3                     183
#define IDB_BITMAP4                     184
#define IDB_BITMAP_BAK                  185
#define IDD_DIALOG_EXPORT               186
#define IDD_DIALOG_MESSAGE_DLG          187
#define IDD_DIALOG_DF_TASK_EDIT         188
#define IDD_DIALOG_TASKS_MGR            190
#define IDD_DIALOG_VERSION_SHOW         191
#define IDC_LIST_TASK_SHOW              1000
#define IDC_STATIC_STATUS               1001
#define IDC_LIST_TASK_SHOW2             1002
#define IDC_EDIT_DATE                   1003
#define IDC_EDIT_TITLE                  1005
#define IDC_CHECK_OPERATOR              1007
#define IDC_COMBO_S_H                   1008
#define IDC_COMBO_MUSIC                 1009
#define IDC_MONTHCALENDAR_MINE          1010
#define IDC_COMBO_CMD                   1010
#define IDC_EDIT_DETAILS                1011
#define IDC_EDIT_CMD                    1012
#define IDC_COMBO_S_M                   1013
#define IDC_COMBO_E_H                   1014
#define IDC_COMBO_E_M                   1015
#define IDC_CHECK_MUSIC                 1016
#define IDC_STATIC_1                    1017
#define IDC_STATIC_2                    1018
#define IDC_STATIC_3                    1019
#define IDC_STATIC_4                    1020
#define IDC_STATIC_5                    1021
#define IDC_STATIC_6                    1022
#define IDC_COMBO_SELECT                1023
#define IDC_EDIT_DEFALUT_FILE           1024
#define IDC_BUTTON_EXPLORER             1025
#define IDC_LIST_MUSIC                  1026
#define IDC_BUTTON_ADD_M                1027
#define IDC_BUTTON_DEL_M                1028
#define IDC_RADIO_FILE_DAY              1029
#define IDC_BUTTON_PLAY_M               1030
#define IDC_STATIC_TIME                 1030
#define IDC_RADIO_FILE_WEEK             1031
#define IDC_STATIC_FILE                 1031
#define IDC_RADIO_FILE_MONTH            1032
#define IDC_ST_TITLE                    1032
#define IDC_RADIO_FILE_USER_DEFINE      1033
#define IDC_ST_S_TIME                   1033
#define IDC_BUTTON_STOP_M               1034
#define IDC_ST_E_TIME                   1034
#define IDC_ST_PERCENT                  1035
#define IDC_ST_DETAILS                  1036
#define IDC_EDIT_BAK_PIC                1036
#define IDC_COMBO_REMIND                1037
#define IDC_EDIT_LOG_VIEWER             1037
#define IDC_STATIC_TITLE                1039
#define IDC_STATIC_TITLE2               1040
#define IDC_STATIC_STIME                1040
#define IDC_STATIC_TITLE3               1041
#define IDC_STATIC_ETIME                1041
#define IDC_STATIC_TITLE4               1042
#define IDC_STATIC_PERCENT              1042
#define IDC_STATIC_DETAILS              1043
#define IDC_EDIT2                       1044
#define IDC_EDIT_MINS                   1044
#define IDC_COMBO_PER                   1045
#define IDC_COMBO_S_H_2                 1046
#define IDC_COMBO_S_M_2                 1047
#define IDC_COMBO_E_H_2                 1048
#define IDC_COMBO_E_M_2                 1049
#define IDC_STATIC_FREE                 1050
#define IDC_STATIC_USED                 1051
#define IDC_STATIC_REDUPLICATE          1052
#define IDC_BTN_CO_FREE                 1053
#define IDC_BTN_CO_USED                 1054
#define IDC_BTN_CO_REDUPLICATE          1055
#define ID_MSG_HANDLE_OK                1055
#define IDC_STATIC_NOT_INCLUDE          1056
#define IDC_STATIC_X1                   1056
#define IDC_BTN_CO_NOT_INC              1057
#define ID_MSG_HANDLE_OK_AND_EDIT       1057
#define IDC_STATIC_CHANGE               1058
#define IDC_BTN_MODIFY_LOG_VIEWER       1058
#define IDC_BTN_DEFAULT_LOG_VIEWER      1059
#define ID_BTN_SAVE                     1060
#define ID_BTN_CANCEL                   1061
#define ID_BTN_SUB_CANCEL               1062
#define ID_BTN_CHG_BAK                  1062
#define ID_SUB_OK                       1063
#define ID_EDIT_OK                      1064
#define ID_EDIT_CANCEL                  1065
#define IDC_CHECK_START_UP              1066
#define ID_CANCEL_EXPORT                1067
#define IDC_BTN_CUR                     1068
#define ID_CANCEL_EDIT_DF               1068
#define IDC_BTN_ALL                     1069
#define IDC_CUR_TIME                    1069
#define IDC_BTN_ALL_BY_DAY              1070
#define IDC_STATIC_MY_ICON              1070
#define IDC_STATIC_VER                  1071
#define IDC_EDIT_EMAIL                  1072
#define IDC_EDIT_MSGTEXT                1074
#define ID_OK_EDIT_DF                   1075
#define ID_EDIT_DF_ADD                  1076
#define IDC_RADIO_DAY                   1076
#define ID_EDIT_DF_DEL                  1077
#define IDC_RADIO_WEEK                  1077
#define ID_EDIT_DF_MODIFY               1078
#define IDC_RADIO_MONTH                 1078
#define IDC_COMBO_WEEK                  1079
#define ID_EDIT_DF_DEL2                 1079
#define ID_EDIT_DF_IMPORT               1079
#define IDC_COMBO_MONTH                 1080
#define ID_EDIT_DF_EXPORT               1080
#define IDC_RADIO_USER_DEFINE           1081
#define IDC_EDIT_DAYS                   1082
#define IDC_EDIT_TITLE_DF               1083
#define IDC_RADIO_CERTAIN_DAY           1084
#define IDC_CHECK_MUSIC_DF              1085
#define IDC_CHECK_OPERATOR_DF           1086
#define IDC_EDIT_CMD_DF                 1087
#define IDC_LIST_DF_TASKS               1088
#define IDC_RADIO_EXCEL                 1089
#define IDC_RADIO_TXT                   1090
#define IDC_STATIC_END_TIME             1090
#define IDC_STATIC_START_TIME           1091
#define IDC_STATIC_PERCENT_TITLE        1092
#define IDC_EDIT_C_DAY                  1095
#define IDC_LIST1                       1096
#define IDC_LIST_VERSION                1096
#define IDC_COMBO_VER_LIST              1098
#define ID_MENU_OPEN                    32772
#define ID_BTN_TOOL_ADD                 32773
#define ID_BTN_TOOL_SAVE                32774
#define ID_BTN_TOOL_EDIT                32775
#define ID_BTN_TOOL_SET                 32779
#define ID_BTN_TOOL_EXIT                32780
#define ID_BTN_TOOL_OPEN                32781
#define ID_BTN_TOOL_DEL                 32782
#define ID_MENU_DEL                     32784
#define ID_MENU_SHOW                    32785
#define ID_MENU_SET                     32786
#define ID_MENU_EDIT                    32788
#define ID_MENU_FINISH                  32789
#define ID_MENU_DO_SOME                 32790
#define ID_BTN_TOOL_SUB                 32791
#define ID_BUTTON32792                  32792
#define ID_BTN_SUB_FINISH               32792
#define ID_BTN_OPEN_DEFAULT             32794
#define ID_BUTTON32795                  32795
#define ID_BTN_SAVE_DEFAULT             32795
#define ID_BUTTON32796                  32796
#define ID_BTN_SAVE_AS                  32796
#define ID_BUTTON32797                  32797
#define ID_BTN_TOOL_SUB_FINISH          32798
#define ID_PROGRESSTEXT                 32799
#define ID_BUTTON32799                  32799
#define ID_BUTTON32800                  32800
#define ID_BTN_TOOL_SAVE_AS             32801
#define ID_BTN_TOOL_OPEN_DEFAULT        32802
#define ID_BTN_TOOL_SAVE_DEFAULT        32803
#define IDM_MENU_SHOW                   32804
#define IDM_MENU_SET                    32805
#define IDM_MENU_EXIT                   32806
#define IDM_MAIN_OPEN_DEFAULT           32807
#define IDM_MAIN_SAVE                   32808
#define IDM_MAIN_SAVE_AS                32809
#define IDM_MAIN_SAVE_DEFAULT           32810
#define IDM_MAIN_EXIT                   32811
#define IDM_MAIN_ADD                    32812
#define IDM_MAIN_DEL                    32813
#define IDM_MAIN_EDIT                   32814
#define IDM_MAIN_SUBMIT                 32815
#define IDM_MAIN_FINISH                 32816
#define IDM_MAIN_COPY                   32818
#define IDM_MAIN_PASTE                  32820
#define IDM_MAIN_COPY_PUB               32821
#define IDM_MAIN_SET                    32822
#define IDM_MAIN_OPEN                   32823
#define IDM_VIEW_LOG                    32824
#define IDM_SET_VIEW_TOOL               32825
#define IDM_MAIN_VIEW_LOG               32826
#define IDM_MAIN_SET_VIEW_TOOL          32827
#define ID_BTN_TOOL_EXPORT              32829
#define ID_BTN_DOT_DEFINED              32831
#define ID_BUTTON000000                 32832
#define IDM_MAIN_EXPORT                 32833
#define IDM_MAIN_EXPORT_ALL             32834
#define IDM_MAIN_EXPORT_EACH            32835
#define IDM_MAIN_CLEAR_COPY             32836
#define IDM_MAIN_DF_TASKS               32837
#define ID_32839                        32839

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        192
#define _APS_NEXT_COMMAND_VALUE         32840
#define _APS_NEXT_CONTROL_VALUE         1099
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
